added login screen
wolox-training/lv-android pull request #1
Opened 2021-09-16 19:40 UTC by Pelozo

__Summary__: Added log-in screen from card U1

__Screenshots__: [original design](https://i.imgur.com/O4WEFzq.jpg) | [implementation](https://i.imgur.com/9WGm6kX.png)

__Known Issues/Notes__: Had to disable WARP (doesn't work in windows)

__Trello Card__: https://trello.com/c/FHt3EAis

2021-09-16 20:26 UTC, ffasitella requested changes
I left some small suggestions!
Excellent job 👍🏽

2021-09-16 20:26 UTC, ffasitella commented on WoloxAndroidBootstrap/app/src/main/java/ar/com/wolox/android/example/ui/login/LoginPresenter.kt
> +    }
You can use `view?.apply`

2021-09-16 20:26 UTC, ffasitella commented on WoloxAndroidBootstrap/app/src/main/java/ar/com/wolox/android/example/utils/ExtensionFunctions.kt
> +package ar.com.wolox.android.example.utils
We should group extension functions by the class they extend. For instance, every String extension function goes to `StringExtensionFunctions.kt`

2021-09-16 20:26 UTC, ffasitella commented on WoloxAndroidBootstrap/app/src/main/res/values/strings.xml
> +    <string name="fragment_signup_terms_and_cond">By joining you agree to our <u>Terms &amp; conditions</u></string>
Use this wording in the login screen, it has the underlined text!

2021-09-16 20:33 UTC, jcruz-wolox approved these changes
Approved for met, good job Leo!

2021-09-17 12:44 UTC, ffasitella approved these changes
Amazing job 🚀 ✨

2021-09-17 13:16 UTC, merged