added home view
wolox-training/lv-android pull request #3
Opened 2021-09-22 14:49 UTC by Pelozo

## Summary:

- Added home screen with news list and profile fragments

## Trello card

- [[U4] Home Page: Tabs de navegación](https://trello.com/c/WpLAqkAJ)

## Preview

![Untitled video ‐ Made with Clipchamp](https://user-images.githubusercontent.com/16638432/134366555-897149d7-4afd-4a3c-88c4-cbc02257ea3c.gif)

2021-09-22 18:16 UTC, jcruz-wolox requested changes
I have any comments:

- Put texts and dimensions in dimens.xml and strings.xml as appropriate.
- The like/dislike print logic can be resolve using selector

2021-09-22 18:16 UTC, jcruz-wolox commented on WoloxAndroidBootstrap/app/src/main/java/ar/com/wolox/android/example/ui/home/news/list/adapter/NewsAdapter.kt
> +            liked.apply {
You can use a selector to solve this logic

2021-09-22 18:16 UTC, jcruz-wolox commented on WoloxAndroidBootstrap/app/src/main/res/layout/fragment_add_new.xml
> +            android:layout_height="56dp"
Remove hardcode dimen

2021-09-22 18:16 UTC, jcruz-wolox commented on WoloxAndroidBootstrap/app/src/main/res/layout/fragment_add_new.xml
> +            android:layout_height="56dp"
Rompe hardcode dime

2021-09-22 18:16 UTC, jcruz-wolox commented on WoloxAndroidBootstrap/app/src/main/res/layout/fragment_home.xml
> +            android:layout_height="48dp"
Remove hardcode dimen

2021-09-22 18:16 UTC, jcruz-wolox commented on WoloxAndroidBootstrap/app/src/main/res/layout/fragment_news.xml
> +            app:maxImageSize="32dp"
Remove hardcode dimen

2021-09-22 18:16 UTC, jcruz-wolox commented on WoloxAndroidBootstrap/app/src/main/res/layout/fragment_profile.xml
> +            android:layout_width="72dp"
Remove hardcode dimen

2021-09-22 18:16 UTC, jcruz-wolox commented on WoloxAndroidBootstrap/app/src/main/res/layout/fragment_profile.xml
> +            android:layout_height="72dp"
Here too

2021-09-22 18:16 UTC, jcruz-wolox commented on WoloxAndroidBootstrap/app/src/main/res/layout/fragment_profile.xml
> +            android:layout_height="48dp"
Here too

2021-09-22 18:16 UTC, jcruz-wolox commented on WoloxAndroidBootstrap/app/src/main/res/layout/fragment_profile.xml
> +            android:textSize="18sp"/>
Here too

2021-09-22 18:16 UTC, jcruz-wolox commented on WoloxAndroidBootstrap/app/src/main/res/layout/fragment_profile.xml
> +            android:textSize="11sp"/>
Here too

2021-09-22 18:16 UTC, jcruz-wolox commented on WoloxAndroidBootstrap/app/src/main/res/layout/fragment_home.xml
> +            app:title="Wolox"
Remove hardcode string

2021-09-22 18:16 UTC, jcruz-wolox commented on WoloxAndroidBootstrap/app/src/main/res/layout/item_new.xml
> +            android:layout_width="48dp"
Remove hardcode dimen

2021-09-22 18:16 UTC, jcruz-wolox commented on WoloxAndroidBootstrap/app/src/main/res/layout/item_new.xml
> +            android:layout_height="48dp"
Here too

2021-09-22 18:16 UTC, jcruz-wolox commented on WoloxAndroidBootstrap/app/src/main/res/layout/item_new.xml
> +            android:textSize="18sp"
Remove hardcode dimen

2021-09-22 20:28 UTC, jcruz-wolox approved these changes
Approved for me.

2021-09-23 12:39 UTC, ffasitella requested changes
Niiice! Just left two style comments

2021-09-23 12:39 UTC, ffasitella commented on WoloxAndroidBootstrap/app/src/main/java/ar/com/wolox/android/example/ui/home/HomeFragment.kt
> +            binding.tabLayout.setupWithViewPager(binding.viewPager)
Just call `setupWithViewPager(viewPager)`

2021-09-23 12:39 UTC, ffasitella commented on WoloxAndroidBootstrap/app/src/main/java/ar/com/wolox/android/example/utils/extensions/StringExtensionFunctions.kt
> +                SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'").parse(this).time
Move this string to a constant

2021-09-23 12:50 UTC, ffasitella approved these changes
![](https://media.giphy.com/media/gVoBC0SuaHStq/giphy.gif?cid=ecf05e47treopgpbjzathx5e3svezud8fhh1ecwhmsk520cp&rid=giphy.gif&ct=g)

2021-09-23 12:51 UTC, merged